### ISSUE TITLE
Add pre-commit

### ISSUE THREAD

**Issue by nstarman** [nstarman/templates#14]
### Description

To ensure that modifications to the templates adhere to coding best practices

### Checklist

- [x] Check out our [contributing guidelines](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md).
- [x] Check out our [code of conduct](https://github.com/astropy/astropy/blob/master/CODE_OF_CONDUCT.md).
- [x] Search the GitHub repository to see if a similar issue has already been posted. If a similar issue is closed, have a quick look to see if you are satisfied by the resolution. If not please go ahead and open an issue!
